title: 敦煌网
description: 买全球，卖全球，赋能中小微企业

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .vscode
  - .idea
  - .devcontainer